<?php
  exec('/opt/boilercontrol/scripts/getfreediskspace.sh', $freediskspace); // This actually returns the used space
  if (!$freediskspace)
    $freediskspace[0]="Unavailable";
  else if ($freediskspace[0] < 85)
    $freediskspacecolor = "green";
  else if ($freediskspace[0] < 95)
    $freediskspacecolor = "orange";
  else
    $freediskspacecolor = "red";
  
  exec('/opt/boilercontrol/scripts/getcputemperature.sh', $cputemperature);
  if (!$cputemperature)
    $cputemperature[0]="--";
  else if ($cputemperature[0] < 700)
    $cputemperaturecolor = "green";
  else if ($cputemperature[0] < 800)
    $cputemperaturecolor = "orange";
  else
    $cputemperaturecolor = "red";
  
    
  exec('cat /opt/boilercontrol/version',$versione);
  exec('cat /var/www/version',$versionw);
  exec('/opt/boilercontrol/scripts/geteth0ip.sh',$ethip);
  if (!$ethip)
    $ethip[0]="Disabled";
  exec('/opt/boilercontrol/scripts/geteth0mac.sh',$ethmac);
  if (!$ethmac)
    $ethip[0]="Unavailable";
  exec('/opt/boilercontrol/scripts/getwlan0ip.sh',$wlanip);
  if (!$wlanip)
    $ethip[0]="Disabled";
  exec('/opt/boilercontrol/scripts/getwlan0mac.sh',$wlanmac);
  if (!$wlanmac)
    $ethip[0]="Unavailable";
  exec('cat /opt/boilercontrol/firstday',$firstday);
  if (!$firstday)
    $firstday[0]=2;
  exec('cat /opt/boilercontrol/temperatureunit',$temperatureunit);
  if (!$temperatureunit)
    $temperatureunit[0]=2;
  exec('cat /opt/boilercontrol/preheat',$preheat);
  if (!$preheat)
    $preheat[0]=30;
  exec('/opt/boilercontrol/scripts/gettz.sh',$tz);
  if (!$tz)
    $tz[0]="GMT";
  exec('/opt/boilercontrol/scripts/getssid.sh', $ssid);
  if (!$ssid)
    $ssid[0]="Disabled";
  exec('/opt/boilercontrol/scripts/getwifiinfo.sh', $wifiinfo);
  if (!$wifiinfo)
    $wifiinfo[0]="--";
  else if ($wifiinfo[0] > 80) 
    $wifiicon = 6;
  else if ($wifiinfo[0] > 60) 
    $wifiicon = 5;
  else if ($wifiinfo[0] > 40) 
    $wifiicon = 4;
  else if ($wifiinfo[0] > 20) 
    $wifiicon = 3;
  else if ($wifiinfo[0] > 10) 
    $wifiicon = 2;
  else 
    $wifiicon = 1;
?>
<script type="text/javascript">
function success(data) {
	var text = "";
	if (data.Result == "ERROR") {
		text = "Error: " + data.Message;
	} else {
		text = "Holiday times set";
	}

	var $dialog = $('<div></div>')
	.html(text)
	.dialog({
		autoOpen: false,
		title: 'Setting holiday times',
		close: function(ev, ui) { $(this).html(text); }
	});

	$dialog.dialog('open');

	$.getJSON("/api/configuration/holidaytimes/", function(json) {
		if(json.Result == "OK") {
			$('#timeString').html(json.Message);
		}
	});
};

$(document).ready(function() { 
	$( "#submit" ).button(); //style button
	
	//Create datetimepickers
	$('#holidayFrom').datetimepicker();
	$('#holidayTo').datetimepicker(); 

	//Submit click functionality
	$('#submit').click(function() {
		$.ajax({
			  type: 'POST',
			  url: "/api/configuration/holiday/",
			  data: {"from": $('#holidayFrom').datetimepicker('getDate'), 
				  "to": $('#holidayTo').datetimepicker('getDate')},
			  success: success,
			  dataType: 'json',
			});
	});

	//Accordian
	$(function() {
		$( "#holidayTimes" ).accordion({ collapsible: true, active: false });
	});
} );

</script>

<div id="settings">
<hr>
  <h3><a href="#">Device Status</a></h3>
<hr>
  <table>
    <tr>
      <td>Used space:</td>
      <td style=color:<?php echo $freediskspacecolor?>><?php echo $freediskspace[0]?></td>
    </tr>
    <tr>
      <td>CPU Temperature:</td>
      <td style=color:<?php echo $cputemperaturecolor?>><?php echo $cputemperature[0]/10?>&#8451;</td>
    </tr>
  </table>
<hr>
	<h3><a href="#">Web Access</a></h3>
<hr>
	<table>
    <tr>
      <td colspan=2>Modify your username or password:</td>
    </tr>
    <tr>
      <td>Username:</td>
      <td><form><input type="text" id="username" /></td>
    </tr>
    <tr>
      <td>Password:</td>
      <td><input type="password" id="password" /></td>
    </tr>
    <tr>
      <td></td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
  </table>
<hr>
	<h3><a href="#">Time Settings</a></h3>
<hr>
	 <table>
    <tr>
      <td>Local Time Zone:</td>
      <td>
        <select name="timezone" id="timezone">
              <option value="-14.0" <?php if ($tz[0]=="GMT-14") echo "selected"?>>(GMT -14:00) Eniwetok, Kwajalein</option>
              <option value="-13.0" <?php if ($tz[0]=="GMT-13") echo "selected"?>>(GMT -13:00) Eniwetok, Kwajalein</option>
              <option value="-12.0" <?php if ($tz[0]=="GMT-12") echo "selected"?>>(GMT -12:00) Eniwetok, Kwajalein</option>
              <option value="-11.0" <?php if ($tz[0]=="GMT-11") echo "selected"?>>(GMT -11:00) Midway Island, Samoa</option>
              <option value="-10.0" <?php if ($tz[0]=="GMT-10") echo "selected"?>>(GMT -10:00) Hawaii</option>
              <option value="-9.0" <?php if ($tz[0]=="GMT-9") echo "selected"?>>(GMT -9:00) Alaska</option>
              <option value="-8.0" <?php if ($tz[0]=="GMT-8") echo "selected"?>>(GMT -8:00) Pacific Time (US &amp; Canada)</option>
              <option value="-7.0" <?php if ($tz[0]=="GMT-7") echo "selected"?>>(GMT -7:00) Mountain Time (US &amp; Canada)</option>
              <option value="-6.0" <?php if ($tz[0]=="GMT-6") echo "selected"?>>(GMT -6:00) Central Time (US &amp; Canada), Mexico City</option>
              <option value="-5.0" <?php if ($tz[0]=="GMT-5") echo "selected"?>>(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima</option>
              <option value="-4.0" <?php if ($tz[0]=="GMT-4") echo "selected"?>>(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz</option>
              <option value="-3.0" <?php if ($tz[0]=="GMT-3") echo "selected"?>>(GMT -3:00) Brazil, Buenos Aires, Georgetown</option>
              <option value="-2.0" <?php if ($tz[0]=="GMT-2") echo "selected"?>>(GMT -2:00) Mid-Atlantic</option>
              <option value="-1.0" <?php if ($tz[0]=="GMT-1") echo "selected"?>>(GMT -1:00) Azores, Cape Verde Islands</option>
              <option value="0.0" <?php if ($tz[0]=="GMT") echo "selected"?>>(GMT) Western Europe Time, London, Lisbon</option>
              <option value="1.0" <?php if ($tz[0]=="GMT+1") echo "selected"?>>(GMT +1:00) Brussels, Copenhagen, Madrid, Paris</option>
              <option value="2.0" <?php if ($tz[0]=="GMT+2" || $tz[0]=="EET") echo "selected"?>>(GMT +2:00) Athens, Cairo, South Africa</option>
              <option value="3.0" <?php if ($tz[0]=="GMT+3") echo "selected"?>>(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg</option>
              <option value="4.0" <?php if ($tz[0]=="GMT+4") echo "selected"?>>(GMT +4:00) Abu Dhabi, Muscat, Tbilisi</option>
              <option value="5.0" <?php if ($tz[0]=="GMT+5") echo "selected"?>>(GMT +5:00) Ekaterinburg, Islamabad</option>
              <option value="6.0" <?php if ($tz[0]=="GMT+6") echo "selected"?>>(GMT +6:00) Almaty, Dhaka, Colombo</option>
              <option value="7.0" <?php if ($tz[0]=="GMT+7") echo "selected"?>>(GMT +7:00) Bangkok, Hanoi, Jakarta</option>
              <option value="8.0" <?php if ($tz[0]=="GMT+8") echo "selected"?>>(GMT +8:00) Beijing, Singapore, Hong Kong</option>
              <option value="9.0" <?php if ($tz[0]=="GMT+9") echo "selected"?>>(GMT +9:00) Tokyo, Seoul, Osaka</option>
              <option value="10.0" <?php if ($tz[0]=="GMT+10") echo "selected"?>>(GMT +10:00) Eastern Australia</option>
              <option value="11.0" <?php if ($tz[0]=="GMT+11") echo "selected"?>>(GMT +11:00) Magadan, Solomon Islands, New Caledonia</option>
              <option value="12.0" <?php if ($tz[0]=="GMT+12") echo "selected"?>>(GMT +12:00) Auckland, Wellington, Fiji</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>First day of week:</td>
      <td>
        <form>
        <input type="radio" name="firstday" value="sunday" <?php if ($firstday[0]=="1") echo "checked"?>>&nbsp;Sunday &nbsp;&nbsp;
        <input type="radio" name="firstday" value="monday" <?php if ($firstday[0]=="2") echo "checked"?>>&nbsp;Monday
      </td>
    </tr>
    <tr>
      <td></td>
      <td align=right><input type="submit" value=" Change " disabled></form></td>
    </tr>
  </table>
<hr>
  <h3><a href="#">Temperature Settings:</a></h3>
<hr>
<table>
    <tr>
      <td>
        <form>
        <!--&deg;C-->
        <input type="radio" name="firstday" value="celsius" <?php if ($temperatureunit[0]=="2") echo "checked"?>>&nbsp;Celsius (&#8451;)&nbsp;&nbsp;
        <input type="radio" name="firstday" value="fahrenheit" <?php if ($temperatureunit[0]=="1") echo "checked"?>>&nbsp;Fahrenheit (&#8457;)&nbsp;&nbsp;
      </td>
      <td align=right><input type="submit" value=" Change " disabled></form></td>
    </tr>
    
  </table>
<hr>
	<h3><a href="#">Network Settings:</a></h3>
<hr>
	Wired connection details:</br>
   <table>
    <tr>
      <td>
        IP Address:
      </td>
      <td>
        <input type="text" id="ip" size="15" value="<?php echo $ethip[0]?>" />
      </td>
    </tr>
    <tr>
      <td>
        MAC Address:
      </td>
      <td>
        <input type="text" id="mac" size="17" value="<?php echo $ethmac[0]?>" />
      </td>
    </tr>
  </table></br>
  Wireless connection details:</br>
   <table>
    <tr>
      <td style="vertical-align: bottom;">
        SSID: <?php echo $ssid[0]?> 
      </td>
      <td >
        <img title="<?php echo $wifiinfo[0]?>%" style="vertical-align: bottom;" src=/images/wifi/<?php echo $wifiicon?>.png>
      </td>
    </tr>
    <tr>
      <td>
        IP Address:
      </td>
      <td>
        <input type="text" id="ip" size="15" value="<?php echo $wlanip[0]?>" />
      </td>
    </tr>
    <tr>
      <td>
        MAC Address:
      </td>
      <td>
        <input type="text" id="mac" size="17" value="<?php echo $wlanmac[0]?>" />
      </td>
    </tr>
  </table></br>
<!--
   <table>
    <tr>
      <td colspan=2>
        <form>
        <input type="radio" name="ipmethod" value="dhcp">&nbsp;Dynamic (DHCP) &nbsp;&nbsp;
        <input type="radio" name="ipmethod" value="static" checked="checked">&nbsp;Static
      </td>
    </tr>
    <tr>
      <td>
        IP Address:
      </td>
      <td>
        <input type="text" id="ip1" size="3" value="192" />.
        <input type="text" id="ip2" size="3" value="168" />.
        <input type="text" id="ip3" size="3" value="1" />.
        <input type="text" id="ip4" size="3" value="100" />
      </td>
    </tr>
    <tr>
      <td>
        Subnet Mask:
      </td>
      <td>
        <input type="text" id="mask1" size="3" value="255" />.
        <input type="text" id="mask2" size="3" value="255" />.
        <input type="text" id="mask3" size="3" value="255" />.
        <input type="text" id="mask4" size="3" value="0" />
      </td>
    </tr>
    <tr>
      <td>
        Default Gateway:
      </td>
      <td>
        <input type="text" id="gateway1" size="3" value="192" />.
        <input type="text" id="gateway2" size="3" value="168" />.
        <input type="text" id="gateway3" size="3" value="1" />.
        <input type="text" id="gateway4" size="3" value="1" />
      </td>
    </tr>
    <tr>
      <td>
        DNS:
      </td>
      <td>
        <input type="text" id="dns1" size="3" value="192" />.
        <input type="text" id="dns2" size="3" value="168" />.
        <input type="text" id="dns3" size="3" value="1" />.
        <input type="text" id="dns4" size="3" value="1" />
      </td>
    </tr>
    <tr>
      <td></td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
  </table></br>
	Wireless connection details:
	<table>
    <tr>
      <td colspan=2>
        <form>
        <input type="radio" name="wirelessipmethod" value="dhcp">&nbsp;Dynamic (DHCP) &nbsp;&nbsp;
        <input type="radio" name="wirelessipmethod" value="static" checked="checked">&nbsp;Static
      </td>
    </tr>
    <tr>
      <td>
        IP Address:
      </td>
      <td>
        <input type="text" id="wirelessip1" size="3" value="192" />.
        <input type="text" id="wirelessip2" size="3" value="168" />.
        <input type="text" id="wirelessip3" size="3" value="1" />.
        <input type="text" id="wirelessip4" size="3" value="110" />
      </td>
    </tr>
    <tr>
      <td>
        Subnet Mask:
      </td>
      <td>
        <input type="text" id="wirelessmask1" size="3" value="255" />.
        <input type="text" id="wirelessmask2" size="3" value="255" />.
        <input type="text" id="wirelessmask3" size="3" value="255" />.
        <input type="text" id="wirelessmask4" size="3" value="0" />
      </td>
    </tr>
    <tr>
      <td>
        Default Gateway:
      </td>
      <td>
        <input type="text" id="wirelessgateway1" size="3" value="192" />.
        <input type="text" id="wirelessgateway2" size="3" value="168" />.
        <input type="text" id="wirelessgateway3" size="3" value="1" />.
        <input type="text" id="wirelessgateway4" size="3" value="1" />
      </td>
    </tr>
    <tr>
      <td>
        DNS:
      </td>
      <td>
        <input type="text" id="wirelessdns1" size="3" value="192" />.
        <input type="text" id="wirelessdns2" size="3" value="168" />.
        <input type="text" id="wirelessdns3" size="3" value="1" />.
        <input type="text" id="wirelessdns4" size="3" value="1" />
      </td>
    </tr>
    <tr>
      <td></td>
      <td align=right><input type="submit" value=" Change "></form></td>
    </tr>
  </table>
-->
<hr>
	<h3><a href="#">Hestia Smart Settings:</a></h3>
<hr>
	<table>
    <tr>
      <td>Boiler Preheat Period:</td>
      <td>
        <select name="preheat" id="preheat">
              <option value="0" <?php if ($preheat[0]=="0") echo "selected"?>>0</option>
              <option value="5" <?php if ($preheat[0]=="5") echo "selected"?>>5</option>
              <option value="10" <?php if ($preheat[0]=="10") echo "selected"?>>10</option>
              <option value="15" <?php if ($preheat[0]=="15") echo "selected"?>>15</option>
              <option value="30" <?php if ($preheat[0]=="30") echo "selected"?>>30</option>
              <option value="45" <?php if ($preheat[0]=="45") echo "selected"?>>45</option>
        </select>
        minutes &nbsp;&nbsp;
      </td>
      <td align=right><input type="submit" value=" Change " disabled></form></td>
    </tr>
  </table>
<hr>
  <h3><a href="#">Extra Tools:</a></h3>
<hr>
  <table>
    <tr>
      <td>
        IR Learning Tool:
      </td>
    </tr>
    <tr>
      <td>
        Make Hestia learn your new IR remote
      </td>
    </tr>
    <tr>
      <td align=right>
        <input type="submit" value=" Start IR Tool ">
        </form>
      </td>
    </tr>
    <tr>
      <td>
        RF Pairing Tool:
      </td>
    </tr>
    <tr>
      <td>
        Pair a new RF module
      </td>
    </tr>
    <tr>
      <td align=right>
        <input type="submit" value=" Pair RF ">
        </form>
      </td>
    </tr>
  </table>



<hr>
  <h3><a href="#">Check for new features:</a></h3>
<hr>
  <table>
    <tr>
      <td>
        Current Engine version:&nbsp;
      </td>
      <td>
        <?php echo $versione[0]?>&nbsp;&nbsp;&nbsp;
      </td>
      <td>
        <form action="http://www.hestiapi.com/upgrade/engine/check-<?php echo $versione[0]?>.htm">
            <input type="submit" value="&nbsp;Check&nbsp;">
        </form>
      </td>
    </tr>
    <tr>
      <td>
        Current Web version:&nbsp;
      </td>
      <td>
        <?php echo $versionw[0]?>&nbsp;&nbsp;&nbsp;
      </td>
      <td>
        <form action="http://www.hestiapi.com/upgrade/web/check-<?php echo $versionw[0]?>.htm">
            <input type="submit" value="&nbsp;Check&nbsp;">
        </form>
      </td>
    </tr>

  </table>



</div>
