<div id="navbar">
	<div id="navbarInner">
		<ul>
		<li><a href="<?= $this->url(array('controller' => 'settings', 'action' => 'index'),'default',true); ?>">settings</a></li>
		<li><a href="<?= $this->url(array('controller' => 'groups', 'action' => 'index'),'default',true); ?>">groups</a></li>
		<li><a href="<?= $this->url(array('controller' => 'schedules', 'action' => 'index'),'default',true); ?>">schedules</a></li>
		<li><a href="<?= $this->url(array('controller' => 'holidays', 'action' => 'index'),'default',true); ?>">holidays</a></li>
		<li><a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'),'default',true); ?>">hestia</a></li>
		</ul>
	</div>
</div>