<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<?= $this->headTitle(); ?>

<?= $this->headMeta(); ?>

<?= $this->headStyle(); ?>

<?= $this->headLink(); ?>

<?= $this->headScript(); ?>

<!--
<link rel="shortcut icon" href="<?php echo $this->baseUrl('/favicon.ico')?>" type="image/x-icon" />
-->

<link href="/images/hestia.png" rel="icon" type="image/x-icon" />
<meta name="apple-mobile-web-app-capable" content="yes">
<link href="/images/hestia.png" rel="apple-touch-icon">
</head>
<body>

<?php echo $this->render('_topnav.phtml') ?>

<div id="wrapper">

<div id="content">
<?= $this->layout()->content; ?>
</div>

<div id="footer">
Information and updates on <a href="http://www.hestiapi.com/" target=_blank>hestiapi.com</a>
</div>

</div>

</body>
</html>
