<?php
include 'hestia.inc';

if($dht11){
  //ToDo: Not always returned a value. 
  //Maybe needs to be called by someone else periodically handling unanswered calls
  //and storing correct values
  exec('/opt/boilercontrol/scripts/gettemperaturedht11.sh',$return);
  //exec('/opt/boilercontrol/scripts/getls.sh',$return);
} else {
  exec('/opt/boilercontrol/scripts/gettemperature.sh',$return);
}

$temp_3f=$return[0]/1000;
$temp_2f = number_format($temp_3f, 2, '.', '');

if($dht11){
  exec('/opt/boilercontrol/scripts/gethumiditydht11.sh',$return);
  $humidity = $return[0];
}
?>
<div class="boost_table">
<table>
<tr>
	<td>Time:</td>
	<td><span id="clock"></span></td>
	<td></td>
</tr>
<tr>
  <td>Temperature:</td>
  <td><span id="temperature"><?php echo $temp_2f?>°C</span></td><!--TODO: Symbol needs to be dynamically read from the db-->
  <td id="heatingset" style="visibility:visible;">Set: <span id="temperatureset">22</span>°C &nbsp;<img id="setminus" src="/images/minus.png" />&nbsp;<img id="setplus" src="/images/plus.png" /></td>
</tr>
<?php
if($dht11){
?>
  <tr>
    <td>Humidity:</td>
    <td><span id="humidity"><?php echo $humidity?>%</span></td>
    <td></td>
  </tr>
<?php
}
?>
</table>
<table>
<tr>
	<td>Heating:</td>
	<td><img id="heating" src="/images/led_off.png" /></td>
	<td>&nbsp;&nbsp;Boost:</td>
	<td class="small"><img id="heatingBoost" src="/images/off.png" /> &nbsp;
		<span id="heatingBoostTime"></span></td>
</tr>
<tr>
  <td>Hot Water:</td>
  <td><img id="water" src="/images/led_off.png" /></td>
  <td>&nbsp;&nbsp;Boost:</td>
  <td class="small"><img id="waterBoost" src="/images/off.png" /> &nbsp;
    <span id="waterBoostTime"></span></td>
</tr>
</table>
</div>

<div id="heating-boost-dialog" title="Set Heating Boost">
  <form>
  <fieldset>
    <label for="heatTime">Boost Time:</label>
    <select name="time" id="heatTime">
    	<option value="1">1 minute</option> <!-- TODO: Remove -->
    	<option value="2">2 minutes</option> <!-- TODO: Remove -->
    	<?php 
    	$default = json.boostTimeH;
    	for ($i = 10; $i <= 180; $i = $i + 10) :
    	?>
    	<option value="<?php echo $i?>"><?php echo $i?> minutes</option>
    	<?php endfor; ?>
    </select>
  </fieldset>
  </form>
</div>

<div id="water-boost-dialog" title="Set Water Boost">
  <form>
  <fieldset>
    <label for="waterTime">Boost Time:</label>
    <select name="time" id="waterTime">
      <option value="1">1 minute</option> <!-- TODO: Remove -->
    	<?php 
    	$default = json.boostTimeW;
    	for ($i = 10; $i <= 180; $i = $i + 10) :
    	?>
    	<option value="<?php echo $i?>" <?php if ($i == $default) echo 'selected="selected"'?>><?php echo $i?> minutes</option>
    	<?php endfor; ?>
    </select>
  </fieldset>
  </form>
</div>

<!-- TODO: Change with a better logic rather than reloading the whole page
Reload only this page every 10min. Dirty way to update the temperature 
-->
<script type="text/javascript">
  var reloadme = setTimeout("location.reload(true);",600000);
</script>
